package cz.brno.candg.ttdmmo.constants;

/**
 * Constant for city names
 *
 * @author lastuvka
 */
public class CityNames {

    private static final String[] STRINGS = {"Kvikalkov", "Mordor", "Rohlenka", "Kraj", "Gondor",
        "Brno", "Praha", "London", "Zagreb", "Tvarozna Lhota",
        "Madrid", "Berlin", "Bern", "Sochi", "Vancouver",
        "Centuria", "Sandwich", "Machackala", "Lexibook", "Patagonie",
        "Reckovice", "Ceska", "Sydney", "Koln", "Sanghai", "Likely",
        "Lily Gap",
        "Lincoln",
        "Lincoln Village",
        "Linda",
        "Linden",
        "Lindsay",
        "Littlerock",
        "Live Oak",
        "Livermore",
        "Livingston",
        "Loch Lomond",
        "Lockeford",
        "Lockwood Valley",
        "Lodgepole",
        "Lodi",
        "Lodoga",
        "Loleta",
        "Loma Linda",
        "Loma Rica",
        "Lompoc",
        "Lone Pine",
        "Long Barn",
        "Long Beach",
        "Lookout",
        "Lookout Peak",
        "Loomis",
        "Los Alamitos",
        "Los Altos",
        "Los Altos Hills",
        "Los Angeles",
        "Los Banos",
        "Los Gatos",
        "Los Molinos",
        "Los Serranos",
        "Lost Hills",
        "Lost Horse-Keys Village",
        "Lotus",
        "Lovelock",
        "Lower Lake",
        "Loyalton",
        "Loyola",
        "Lucas Valley-Marinwood",
        "Lucerne",
        "Ludlow",
        "Luther Pass",
        "Lynwood",
        "Lyonsville",
        "Macdoel",
        "Madeline",
        "Madera",
        "Madison",
        "Manton",
        "Manzanita Lake",
        "Maple Creek",
        "March Afb",
        "Marina",
        "Marina Del Rey",
        "Mariposa",
        "Markleeville",
        "Martinez",
        "Marysville",
        "Mather Afb",
        "Maxwell",
        "Yoder",
        "Acme",
        "Sointula",
        "Sooke",
        "Sorrento",
        "Squamish",
        "Stephen",
        "Stewart",
        "Sturdies Bay",
        "Summerland",
        "Surrey",
        "Tahsis",
        "Tappen",
        "Taylor",
        "Telegraph Creek",
        "Terrace",
        "Tlell",
        "Tofino",
        "Trail",
        "Tsawwassen",
        "Ucluelet",
        "Union Bay",
        "Valemount",
        "Vancouver",
        "Vanderhoof",
        "Vernon",
        "Victoria",
        "*Vienna",
        "Linz-Wels-Steyr",
        "Graz",
        "Linz",
        "Salzburg",
        "Innsbruck",
        "Klagenfurt am Wörthersee",
        "Villach",
        "Wels",
        "Sankt Pölten",
        "Dornbirn",
        "Steyr",
        "Wiener Neustadt",
        "Feldkirch",
        "Bregenz",
        "Wolfsberg",
        "Baden",
        "Klosterneuburg",
        "Leoben",
        "Weinzierl bei Krems",
        "Traun",
        "Krems an der Donau",
        "Amstetten",
        "Leonding",
        "Kapfenberg",
        "Mödling",
        "Lustenau",
        "Hallein",
        "Braunau am Inn",
        "Spittal an der Drau",
        "Traiskirchen",
        "Saalfelden am Steinernen Meer",
        "Kufstein",
        "Schwechat",
        "Ternitz",
        "Ansfelden",
        "Stockerau",
        "Feldkirchen in Kärnten",
        "Bad Ischl",
        "Tulln",
        "*Warsaw",
        "Łódź",
        "Kraków",
        "Wrocław",
        "Poznań",
        "Gdańsk",
        "Szczecin",
        "Bydgoszcz",
        "Lublin",
        "Katowice",
        "Białystok",
        "Gdynia",
        "Częstochowa",
        "Sosnowiec",
        "Radom",
        "Toruń",
        "Kielce",
        "Gliwice",
        "Zabrze",
        "Bytom",
        "Bielsko-Biała",
        "Olsztyn",
        "Rzeszów",
        "Ruda Śląska",
        "Rybnik",
        "Dąbrowa Górnicza",
        "Tychy",
        "Opole",
        "Elblag",
        "Laughton",
        "Leamington",
        "Leeds",
        "Leek",
        "Leicester",
        "Leigh",
        "Letchworth",
        "Lewes",
        "Leyland",
        "Lichfield",
        "Lincoln",
        "Little Chalfont",
        "Liverpool",
        "London",
        "Loughborough",
        "Louth",
        "Lowestoft",
        "Luton",
        "Kabul",
        "Kandahār",
        "Mazār-e Sharīf",
        "Herāt",
        "Jalālābād",
        "Kunduz",
        "Ghazni",
        "Balkh",
        "Baghlān",
        "Gardēz",
        "*Tokyo",
        "Yokohama-shi",
        "Ōsaka-shi",
        "Nagoya-shi",
        "Sapporo-shi",
        "Kōbe-shi",
        "Kyoto",
        "Fukuoka-shi",
        "Kawasaki",
        "Saitama"};

    public static String getName(int index) {
        int count = namesCount();
        if (index >= count) {
            int index2 = index % count;
            return STRINGS[index2] + " " + (index / count);
        }
        return STRINGS[index];
    }

    public static int namesCount() {
        return STRINGS.length;
    }
}
